<?php
function getPrinterErrorMessage($brand, $code) {
    $errors = [
        'HP' => [
            0     => 'No Error',
            1     => 'Other Error',
            2     => 'Unknown Error',
            3     => 'Cover Open',
            4     => 'Paper Jam',
            5     => 'Paper Out',
            6     => 'Toner Low',
            7     => 'Toner Empty',
            8     => 'Printer Offline',
            9     => 'Service Requested',
            10    => 'Input Tray Empty',
            11    => 'Output Tray Full',
            12    => 'Door Open',
            13    => 'Cooling Down',
            14    => 'Warming Up',
            15    => 'General Error',
            16    => 'Memory Full',
            17    => 'Print Overrun',
            18    => 'Paper Size Mismatch',
            19    => 'Duplex Unit Error',
            20    => 'Fuser Error',
            21    => 'Scanner Error',
            22    => 'Printhead Missing',
            23    => 'Printhead Failure',
            24    => 'Cartridge Missing',
            25    => 'Cartridge Problem',
            26    => 'Low Maintenance Kit',
            27    => 'Maintenance Kit Needed',
            28    => 'Formatter Error',
            29    => 'Firmware Error',
            30    => 'Network Error',
        ],
        'Canon' => [
            0     => 'No Error',
            1     => 'Unknown Problem',
            2     => 'Paper Jam',
            3     => 'No Paper',
            4     => 'Ink Low',
            5     => 'Ink Empty',
            6     => 'Cover Open',
            7     => 'Cartridge Error',
            8     => 'Service Needed',
            9     => 'Offline',
            10    => 'Error in Output Tray',
            11    => 'Cooling',
            12    => 'Maintenance Required',
            13    => 'Internal Error',
            14    => 'Waste Ink Tank Full',
            15    => 'Print Head Error',
            16    => 'Cannot Detect Cartridge',
            17    => 'Paper Size Error',
            18    => 'Scanner Error',
            19    => 'Ink Absorber Full',
            20    => 'Cover Closed Improperly',
            21    => 'Communication Error',
            22    => 'USB Connection Error',
            23    => 'Network Error',
            24    => 'Firmware Corrupted',
            25    => 'Hardware Fault',
        ]
    ];

    $brand = ucfirst(strtolower($brand));
    return $errors[$brand][$code] ?? "Unknown Error Code ($code)";
}
?>
